# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # enum: `egress_vlan_names`, `gbp_tag`, `match`, `radius_attrs`,
  # `radius_group`, `radius_vendor_attrs`, `session_timeout`, `username_attr`,
  # `vlan`
  class NacTagTypeEnum
    NAC_TAG_TYPE_ENUM = [
      # TODO: Write general description for EGRESS_VLAN_NAMES
      EGRESS_VLAN_NAMES = 'egress_vlan_names'.freeze,

      # TODO: Write general description for GBP_TAG
      GBP_TAG = 'gbp_tag'.freeze,

      # TODO: Write general description for MATCH
      MATCH = 'match'.freeze,

      # TODO: Write general description for RADIUS_ATTRS
      RADIUS_ATTRS = 'radius_attrs'.freeze,

      # TODO: Write general description for RADIUS_GROUP
      RADIUS_GROUP = 'radius_group'.freeze,

      # TODO: Write general description for RADIUS_VENDOR_ATTRS
      RADIUS_VENDOR_ATTRS = 'radius_vendor_attrs'.freeze,

      # TODO: Write general description for SESSION_TIMEOUT
      SESSION_TIMEOUT = 'session_timeout'.freeze,

      # TODO: Write general description for USERNAME_ATTR
      USERNAME_ATTR = 'username_attr'.freeze,

      # TODO: Write general description for VLAN
      VLAN = 'vlan'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_TAG_TYPE_ENUM.include?(value)
    end
  end
end
