# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # nac_tag_username_attr_enum.
  class NacTagUsernameAttrEnum
    NAC_TAG_USERNAME_ATTR_ENUM = [
      # TODO: Write general description for AUTOMATIC
      AUTOMATIC = 'automatic'.freeze,

      # TODO: Write general description for CN
      CN = 'cn'.freeze,

      # TODO: Write general description for UPN
      UPN = 'upn'.freeze,

      # TODO: Write general description for EMAIL
      EMAIL = 'email'.freeze,

      # TODO: Write general description for DNS
      DNS = 'dns'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_TAG_USERNAME_ATTR_ENUM.include?(value)
    end
  end
end
