# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # if `type`==`marvis_client`. enum: `wireless`, `wireless+wired`
  class NacPortalAccessTypeEnum
    NAC_PORTAL_ACCESS_TYPE_ENUM = [
      # TODO: Write general description for WIRELESS
      WIRELESS = 'wireless'.freeze,

      # TODO: Write general description for ENUM_WIRELESSWIRED
      ENUM_WIRELESSWIRED = 'wireless+wired'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_PORTAL_ACCESS_TYPE_ENUM.include?(value)
    end
  end
end
