# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # enum: `allow`, `block`
  class NacRuleActionEnum
    NAC_RULE_ACTION_ENUM = [
      # TODO: Write general description for ALLOW
      ALLOW = 'allow'.freeze,

      # TODO: Write general description for BLOCK
      BLOCK = 'block'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_RULE_ACTION_ENUM.include?(value)
    end
  end
end
