# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # NacCrlFile Model.
  class NacCrlFile < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Time at which the file was first uploaded, in epoch
    # @return [Float]
    attr_accessor :created_time

    # ID for file upload, used to identify file even for deletion
    # @return [String]
    attr_accessor :id

    # Time at which the file was last updated, in epoch
    # @return [Float]
    attr_accessor :modified_time

    # Name for the .crl file issuer if set
    # @return [String]
    attr_accessor :name

    # Download URL for the .crl file
    # @return [String]
    attr_accessor :url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['created_time'] = 'created_time'
      @_hash['id'] = 'id'
      @_hash['modified_time'] = 'modified_time'
      @_hash['name'] = 'name'
      @_hash['url'] = 'url'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        created_time
        id
        modified_time
        name
        url
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(created_time = SKIP, id = SKIP, modified_time = SKIP,
                   name = SKIP, url = SKIP)
      @created_time = created_time unless created_time == SKIP
      @id = id unless id == SKIP
      @modified_time = modified_time unless modified_time == SKIP
      @name = name unless name == SKIP
      @url = url unless url == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      created_time = hash.key?('created_time') ? hash['created_time'] : SKIP
      id = hash.key?('id') ? hash['id'] : SKIP
      modified_time = hash.key?('modified_time') ? hash['modified_time'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      url = hash.key?('url') ? hash['url'] : SKIP

      # Create object from extracted values.
      NacCrlFile.new(created_time,
                     id,
                     modified_time,
                     name,
                     url)
    end
  end
end
