# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # nac_portal_type_enum.
  class NacPortalTypeEnum
    NAC_PORTAL_TYPE_ENUM = [
      # TODO: Write general description for MARVIS_CLIENT
      MARVIS_CLIENT = 'marvis_client'.freeze,

      # TODO: Write general description for GUEST
      GUEST = 'guest'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_PORTAL_TYPE_ENUM.include?(value)
    end
  end
end
