# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # NacPortalSsoRoleMatching Model.
  class NacPortalSsoRoleMatching < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :assigned

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :match

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['assigned'] = 'assigned'
      @_hash['match'] = 'match'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        assigned
        match
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(assigned = SKIP, match = SKIP)
      @assigned = assigned unless assigned == SKIP
      @match = match unless match == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      assigned = hash.key?('assigned') ? hash['assigned'] : SKIP
      match = hash.key?('match') ? hash['match'] : SKIP

      # Create object from extracted values.
      NacPortalSsoRoleMatching.new(assigned,
                                   match)
    end
  end
end
