# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # enum: `wired`, `wireless`
  class NacRuleMatchingPortTypeEnum
    NAC_RULE_MATCHING_PORT_TYPE_ENUM = [
      # TODO: Write general description for WIRED
      WIRED = 'wired'.freeze,

      # TODO: Write general description for WIRELESS
      WIRELESS = 'wireless'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      NAC_RULE_MATCHING_PORT_TYPE_ENUM.include?(value)
    end
  end
end
