# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # NetworkInternalAccess Model.
  class NetworkInternalAccess < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [TrueClass | FalseClass]
    attr_accessor :enabled

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['enabled'] = 'enabled'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        enabled
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(enabled = SKIP)
      @enabled = enabled unless enabled == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      enabled = hash.key?('enabled') ? hash['enabled'] : SKIP

      # Create object from extracted values.
      NetworkInternalAccess.new(enabled)
    end
  end
end
