# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # NetworkDestinationNatProperty Model.
  class NetworkDestinationNatProperty < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :internal_ip

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :name

    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :port

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['internal_ip'] = 'internal_ip'
      @_hash['name'] = 'name'
      @_hash['port'] = 'port'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      %w[
        internal_ip
        name
        port
      ]
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(internal_ip = SKIP, name = SKIP, port = SKIP)
      @internal_ip = internal_ip unless internal_ip == SKIP
      @name = name unless name == SKIP
      @port = port unless port == SKIP
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      internal_ip = hash.key?('internal_ip') ? hash['internal_ip'] : SKIP
      name = hash.key?('name') ? hash['name'] : SKIP
      port = hash.key?('port') ? hash['port'] : SKIP

      # Create object from extracted values.
      NetworkDestinationNatProperty.new(internal_ip,
                                        name,
                                        port)
    end
  end
end
