# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # ResponseSsoFailureSearch Model.
  class ResponseSsoFailureSearch < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [Array[ResponseSsoFailureSearchItem]]
    attr_accessor :results

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['results'] = 'results'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(results = nil)
      @results = results
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      results = nil
      unless hash['results'].nil?
        results = []
        hash['results'].each do |structure|
          results << (ResponseSsoFailureSearchItem.from_hash(structure) if structure)
        end
      end

      results = nil unless hash.key?('results')

      # Create object from extracted values.
      ResponseSsoFailureSearch.new(results)
    end
  end
end
