# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # ResponseSsoFailureSearchItem Model.
  class ResponseSsoFailureSearchItem < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :detail

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :saml_assertion_xml

    # TODO: Write general description for this method
    # @return [Float]
    attr_accessor :timestamp

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['detail'] = 'detail'
      @_hash['saml_assertion_xml'] = 'saml_assertion_xml'
      @_hash['timestamp'] = 'timestamp'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(detail = nil, saml_assertion_xml = nil, timestamp = nil)
      @detail = detail
      @saml_assertion_xml = saml_assertion_xml
      @timestamp = timestamp
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      detail = hash.key?('detail') ? hash['detail'] : nil
      saml_assertion_xml =
        hash.key?('saml_assertion_xml') ? hash['saml_assertion_xml'] : nil
      timestamp = hash.key?('timestamp') ? hash['timestamp'] : nil

      # Create object from extracted values.
      ResponseSsoFailureSearchItem.new(detail,
                                       saml_assertion_xml,
                                       timestamp)
    end
  end
end
