# mist_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MistApi
  # Utility class for custom header authorization.
  class ApiToken < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'ApiToken: authorization is undefined.'
    end

    # Initialization constructor.
    def initialize(api_token_credentials)
      auth_params = {}
      auth_params['Authorization'] = api_token_credentials.authorization unless
        api_token_credentials.nil? || api_token_credentials.authorization.nil?

      super auth_params
    end
  end

  # Data class for ApiTokenCredentials.
  # Data class for ApiTokenCredentials.
  class ApiTokenCredentials
    attr_reader :authorization

    def initialize(authorization:)
      raise ArgumentError, 'authorization cannot be nil' if authorization.nil?

      @authorization = authorization
    end

    def clone_with(authorization: nil)
      authorization ||= self.authorization

      ApiTokenCredentials.new(authorization: authorization)
    end
  end
end
